ARG GO_VERSION=1.16

FROM golang:"${GO_VERSION}"-alpine

RUN apk add --no-cache curl jq git build-base bash zip

WORKDIR /
RUN wget -O gh.tar.gz https://github.com/cli/cli/releases/download/v1.11.0/gh_1.11.0_linux_386.tar.gz && \
    tar -xzvf gh.tar.gz && \
    mv gh_1.11.0_linux_386/bin/gh /usr/local/bin/gh && \
    rm -rf gh_1.11.0_linux_386 *.tar.gz
